/**
 * lang.js — Centralized language strings
 * Default: English | Optional: Hinglish (--lang hi)
 *
 * Usage:
 *   const { t } = require('./lang');
 *   console.log(t('seo.titleMissing'));
 */

const strings = {
  en: {
    // ─── CLI / bin/index.js ───────────────────────────────
    cli: {
      version: "Show version",
      jsonFlag: "Output results as JSON in terminal",
      onlyFlag: "Run only specific modules (comma-separated: seo,performance,tech,accessibility,links)",
      exportFlag: "Save report to file (e.g. --export ./report)",
      formatFlag: "Export format: html | json | both (default: html)",
      noLinksFlag: "Skip link checking (faster results)",
      silentFlag: "Hide spinners and progress output",
      langFlag: "Language: en (default) | hi (Hinglish)",
      exportBoth: "Export both HTML and JSON",
      noArgsHelp: "Run --help for usage",
      errorPrefix: "Error",
      errorNotFound: "→ Check the URL and your internet connection",
      errorInvalidUrl: "→ Example: website-analyzer https://google.com",
      errorTimeout: "→ Site is too slow or not responding",
      errorHelp: "For help, run: website-analyzer --help",
      interrupted: "⚠️  Analysis interrupted by user",
    },

    // ─── src/index.js ─────────────────────────────────────
    analyze: {
      noUrl: "Provide a URL! Example: website-analyzer https://google.com",
      invalidUrl: (url) => `Invalid URL: "${url}" — provide a valid URL, e.g. https://google.com`,
      fetching: (url) => `Fetching ${url}...`,
      fetchDone: (ms, code) => `Fetched! (${ms}ms, HTTP ${code})`,
      fetchFail: "Fetch failed!",
      analyzingSeo: "Analyzing SEO...",
      seoResult: (pct, grade) => `SEO analyzed — ${pct}% (${grade})`,
      seoFail: "SEO analysis failed",
      detectingTech: "Detecting tech stack...",
      techResult: (count) => `Tech stack — ${count} technologies detected`,
      techFail: "Tech stack detection failed",
      analyzingPerf: "Analyzing performance...",
      perfResult: (pct, grade) => `Performance — ${pct}% (${grade})`,
      perfFail: "Performance analysis failed",
      analyzingA11y: "Checking accessibility...",
      a11yResult: (pct, grade) => `Accessibility — ${pct}% (${grade})`,
      a11yFail: "Accessibility check failed",
      checkingLinks: "Checking links (may take a moment)...",
      linksResult: (total, broken) => `Links — ${total} found, ${broken} broken`,
      linksFail: "Link check failed",
      analyzingSecurity: "Checking security headers...",
      securityResult: (pct, grade) => `Security — ${pct}% (${grade})`,
      securityFail: "Security check failed",
      analyzingSitemap: "Analyzing sitemap...",
      sitemapResult: (pct, grade) => `Sitemap — ${pct}% (${grade})`,
      sitemapFail: "Sitemap analysis failed",
      analyzingRobots: "Analyzing robots.txt...",
      robotsResult: (pct, grade) => `Robots.txt — ${pct}% (${grade})`,
      robotsFail: "Robots.txt analysis failed",
      analyzingSchema: "Analyzing structured data...",
      schemaResult: (pct, grade) => `Schema — ${pct}% (${grade})`,
      schemaFail: "Schema analysis failed",
      exporting: "Exporting report...",
      exportDone: "Report exported!",
      exportFail: (msg) => `Export failed: ${msg}`,
      analysisError: (name, msg) => `${name} analysis error: ${msg}`,
    },

    // ─── src/utils/reporter.js ────────────────────────────
    reporter: {
      title: "🔍 WEBSITE ANALYZER REPORT",
      urlLabel: "URL     : ",
      scannedLabel: "Scanned : ",
      timeLabel: "Time    : ",
      overallScores: "📊 OVERALL SCORES",
      techStack: "🛠️  TECH STACK",
      noTechFound: "No technologies detected",
      catSeo: "SEO",
      catPerformance: "Performance",
      catAccessibility: "Accessibility",
      catLinks: "Links",
      catOverall: "OVERALL",
      colCategory: "Category",
      colScore: "Score",
      colGrade: "Grade",
      colStatus: "Status",
      colBar: "Bar",
      colTechCategory: "Category",
      colTechnologies: "Technologies",
      seoAnalysis: "🔍 SEO ANALYSIS",
      perfAnalysis: "⚡ PERFORMANCE ANALYSIS",
      a11yAnalysis: "♿ ACCESSIBILITY ANALYSIS",
      linksAnalysis: "🔗 LINKS ANALYSIS",
      issues: "❌ Issues (fix these):",
      warnings: "⚠️  Warnings (consider improving):",
      passed: "✅ Passed:",
      brokenLinks: "🔴 Broken Links:",
      moreLinks: (n) => `... and ${n} more`,
      redirects: "🔀 Redirects:",
      colLinkType: "Type",
      colCount: "Count",
      totalLinks: "Total Links",
      internalLinks: "Internal Links",
      externalLinks: "External Links",
      brokenLinksCount: "Broken Links",
      redirectCount: "Redirects",
      nofollowCount: "Nofollow",
      mailtoLinks: "Mailto Links",
      telLinks: "Tel Links",
      skipped: "Skipped (limit)",
      colSeoData: "SEO Data",
      colValue: "Value",
      colMetric: "Metric",
      footer: "Made with ❤️  | website-analyzer-cli | github.com/website-analyzer",
      gradeExcellent: "Excellent",
      gradeGood: "Good",
      gradeAverage: "Average",
      gradePoor: "Poor",
      gradeVeryPoor: "Very Poor",
    },

    // ─── src/analyzers/seo.js ─────────────────────────────
    seo: {
      titleMissing: "Title tag is missing!",
      titleOk: (t) => `Title: "${t}"`,
      titleTooShort: (n) => `Title is ${n} chars — ideal: 30-60 chars`,
      titleTooLong: (n) => `Title is ${n} chars — ideal: 30-60 chars`,
      titleLengthOk: (n) => `Title length is good (${n} chars)`,
      metaMissing: "Meta description is missing!",
      metaOk: (d) => `Meta description: "${d}..."`,
      metaLength: (n) => `Meta description is ${n} chars — ideal: 120-160`,
      metaLengthOk: (n) => `Meta description length is good (${n} chars)`,
      canonicalMissing: "Canonical URL not set — may cause duplicate content issues",
      canonicalOk: (c) => `Canonical: ${c}`,
      robotsBlocked: (r) => `robots meta "${r}" — page will not be indexed by Google!`,
      robotsOk: (r) => r ? `Robots: ${r}` : "No robots restriction (indexable)",
      ogMissing: "Open Graph tags missing — links won't show previews on social media",
      ogPartial: (n) => `Only ${n}/5 OG tags set — add more for better previews`,
      ogOk: (n) => `OG tags set (${n}/5)`,
      twitterMissing: "Twitter card meta missing — no preview on Twitter/X",
      twitterOk: (c) => `Twitter card: ${c}`,
      h1Missing: "H1 heading missing — main topic of page is unclear",
      h1Ok: (t) => `H1: "${t}"`,
      h1Multiple: (n) => `${n} H1 tags found — only one should exist`,
      h1Single: "Single H1 tag ✓",
      imgAltMissing: (n, t) => `${n}/${t} images are missing alt text`,
      imgAltOk: (n) => `All ${n} images have alt text ✓`,
      schemaMissing: "No structured data — rich snippets won't appear in Google",
      schemaOk: (n) => `Schema.org structured data found (${n} script)`,
      viewportMissing: "Viewport meta missing — mobile SEO will suffer!",
      viewportOk: (v) => `Viewport: ${v}`,
    },

    // ─── src/analyzers/performance.js ─────────────────────
    performance: {
      noHttps: "Site is using HTTP — HTTPS is missing! Security risk + SEO penalty",
      httpsOk: "HTTPS enabled ✓",
      responseSlow: (ms) => `Response time ${ms}ms — very slow! Check hosting/server`,
      responseWarn: (ms) => `Response time ${ms}ms — could be faster`,
      responseFast: (ms) => `Response time ${ms}ms — fast! ✓`,
      pageLarge: (kb) => `Page size ${kb}KB — too large! Compress images and assets`,
      pageWarn: (kb) => `Page size ${kb}KB — consider optimizing`,
      pageOk: (kb) => `Page size ${kb}KB — looks good ✓`,
      noCompression: "No content compression — enable gzip/brotli to save bandwidth",
      compressionOk: (enc) => `Compression: ${enc} ✓`,
      noCache: "Cache headers missing — browser will re-fetch on every visit",
      cacheOk: (c) => `Caching set (${c || "etag/last-modified"}) ✓`,
      tooManyScripts: (n) => `${n} external scripts — too many! (ideal: ≤10) Page will be slow`,
      scriptsOk: (n) => `Script count: ${n} ✓`,
      tooManyStyles: (n) => `${n} stylesheets — too many (ideal: ≤5)`,
      stylesOk: (n) => `Stylesheet count: ${n} ✓`,
      renderBlocking: (n) => `${n} render-blocking scripts — add async/defer`,
      noRenderBlocking: "No render-blocking scripts ✓",
      oldImageFormats: (n) => `${n} images in old format (JPG/PNG) — use WebP`,
      modernImages: "Images are in modern format ✓",
      badStatus: (code) => `HTTP ${code} — site is not properly accessible!`,
      statusOk: (code) => `HTTP ${code} OK ✓`,
    },

    // ─── src/analyzers/accessibility.js ───────────────────
    accessibility: {
      langMissing: '<html lang="..."> missing — screen readers cannot detect language',
      langOk: (l) => `Language set: "${l}" ✓`,
      imgAltMissing: (n, t) => `${n}/${t} images are missing alt attribute`,
      imgAltOk: (n) => `All ${n} images have alt text ✓`,
      h1Missing: "No H1 on page — main heading is missing",
      h1Ok: "H1 heading present ✓",
      h1Multiple: (n) => `${n} H1 tags found — only 1 should exist`,
      h1Single: "Single H1 ✓",
      headingSkip: "Heading levels are skipped (e.g. H1 → H3) — H2 is missing",
      headingOk: "Heading hierarchy is in correct order ✓",
      inputsUnlabeled: (n, t) => `${n}/${t} form inputs are unlabeled — problem for screen readers`,
      inputsOk: (n) => `All ${n} form inputs are labeled ✓`,
      emptyButtons: (n) => `${n} buttons have no text/aria-label — invisible to screen readers`,
      buttonsOk: (n) => `All ${n} buttons are accessible ✓`,
      genericLinks: (links) => `Generic link text found: ${links.join(", ")} — use descriptive text`,
      linksOk: "Links are descriptive ✓",
      skipNavMissing: "Skip to main content link missing — helpful for keyboard users",
      skipNavOk: "Skip navigation link present ✓",
      noLandmarks: "No ARIA landmarks — difficult to navigate for screen readers",
      fewLandmarks: (n) => `Only ${n}/4 ARIA landmarks — add main, nav, header, footer`,
      landmarksOk: (n) => `${n}/4 ARIA landmarks present ✓`,
      badTabindex: (n) => `${n} elements have tabindex > 0 — tab order will be disrupted`,
      tabindexOk: "tabindex is used correctly ✓",
      zoomDisabled: "Viewport zoom is disabled — problem for visually impaired users!",
      zoomOk: "User zoom is enabled ✓",
    },

    // ─── src/analyzers/links.js ───────────────────────────
    links: {
      brokenFound: (n) => `${n} broken links found — fix or remove them`,
      nobroken: "No broken links ✓",
      redirectsFound: (n) => `${n} links are redirecting — update the URLs`,
      noRedirects: "No unnecessary redirects ✓",
      noInternal: "No internal links — add navigation links",
      internalOk: (n) => `${n} internal links ✓`,
      noExternal: "No external links — link to trusted sources",
      externalOk: (n) => `${n} external links ✓`,
      nofollowOk: (n) => `${n} nofollow links (OK) ✓`,
    },

    // ─── src/utils/fetcher.js ─────────────────────────────
    fetcher: {
      notFound: (url) => `Domain not found: "${url}" — check the URL`,
      connRefused: "Connection refused: server did not respond",
      timeout: (ms) => `Timeout: website did not respond within ${ms}ms`,
      fetchError: (msg) => `Fetch error: ${msg}`,
    },

    // ─── src/analyzers/security.js ────────────────────────
    security: {
      noHttps: "Site is using HTTP — enable HTTPS urgently! Security risk!",
      httpsOk: "HTTPS enabled ✓",
      hstsMissing: "Strict-Transport-Security header missing — browsers won't force HTTPS",
      hstsOk: (v) => `HSTS set: ${v} ✓`,
      hstsMaxAge: (n) => `HSTS max-age ${n}s — should be at least 1 year (31536000)`,
      hstsMaxAgeOk: (n) => `HSTS max-age ${n}s (>= 1 year) ✓`,
      cspMissing: "Content-Security-Policy missing — no protection against XSS attacks",
      cspOk: "CSP header is set ✓",
      cspUnsafeInline: "CSP has 'unsafe-inline' — XSS risk remains",
      cspUnsafeInlineOk: "CSP has no unsafe-inline ✓",
      cspUnsafeEval: "CSP has 'unsafe-eval' — JS injection risk",
      cspUnsafeEvalOk: "CSP has no unsafe-eval ✓",
      xframeMissing: "X-Frame-Options missing — Clickjacking attack possible",
      xframeOk: (v) => `X-Frame-Options: ${v} ✓`,
      xctMissing: "X-Content-Type-Options: nosniff missing — MIME sniffing attack possible",
      xctOk: "X-Content-Type-Options: nosniff ✓",
      referrerWeak: (v) => `Referrer-Policy "${v}" is weak — use strict-origin`,
      referrerMissing: "Referrer-Policy header missing",
      referrerOk: (v) => `Referrer-Policy: ${v} ✓`,
      permsMissing: "Permissions-Policy missing — camera/mic/location access unrestricted",
      permsOk: "Permissions-Policy is set ✓",
      serverLeaks: (s, x) => [s ? `Server version exposed: "${s}"` : "", x ? `X-Powered-By exposed: "${x}" — remove it!` : ""].filter(Boolean).join(" | "),
      serverHidden: "Server info is hidden ✓",
      mixedContent: (n) => `${n} HTTP resources found on HTTPS page — browser may block them`,
      noMixedContent: "No mixed content ✓",
      corsWildcard: "Access-Control-Allow-Origin: * — all domains allowed! Restrict this",
      corsOk: (v) => `CORS restricted: ${v} ✓`,
    },
    // src/analyzers/sitemap.js
    sitemap: {
      notFound: 'Sitemap.xml not found — Google crawling will be affected',
      found: (url) => `Sitemap found: ${url} ✓`,
      indexEmpty: 'Sitemap index found but has no child sitemaps',
      indexFound: (n) => `Sitemap index with ${n} sitemaps ✓`,
      noUrls: 'Sitemap has no URLs — check your sitemap generator',
      urlCount: (n) => `Sitemap has ${n} URLs ✓`,
      tooLarge: (n) => `Sitemap has ${n} URLs — exceeds 50,000 limit! Split into multiple sitemaps`,
      sizeOk: (n) => `Sitemap size OK (${n} URLs) ✓`,
      noLastmod: 'No lastmod dates — add last modified dates for better crawling',
      hasLastmod: 'Sitemap has lastmod dates ✓',
      invalidXml: 'Sitemap XML format is invalid',
      validXml: 'Sitemap XML is valid ✓',
      httpUrls: (n) => `${n} URLs in sitemap use HTTP instead of HTTPS`,
      httpsUrls: 'All sitemap URLs use HTTPS ✓',
    },
    // src/analyzers/robots.js
    robots: {
      notFound: 'robots.txt not found — crawlers have no instructions',
      found: (url) => `robots.txt found: ${url} ✓`,
      noSitemapRef: 'No Sitemap reference in robots.txt — add Sitemap: https://yoursite.com/sitemap.xml',
      hasSitemapRef: (url) => `Sitemap referenced: ${url} ✓`,
      noWildcard: 'No User-agent: * rule — all crawlers have no default instructions',
      hasWildcard: 'Wildcard User-agent (*) defined ✓',
      blocksAll: 'Disallow: / for all crawlers — entire site is blocked from indexing!',
      notBlockingAll: 'Site is not blocking all crawlers ✓',
      noGooglebot: 'No Googlebot rules — add specific rules for Google crawler',
      hasGooglebot: 'Googlebot rules defined ✓',
      crawlDelayHigh: (n) => `Crawl-delay: ${n}s is too high — crawlers will be slow`,
      crawlDelayOk: (n) => `Crawl-delay: ${n}s is reasonable ✓`,
      noSensitiveBlock: 'No sensitive paths blocked (e.g. /admin, /login) — consider blocking them',
      hasSensitiveBlock: (paths) => `Sensitive paths blocked: ${paths} ✓`,
      tooLarge: (kb) => `robots.txt is ${kb}KB — too large, keep it under 500KB`,
      sizeOk: (kb) => `robots.txt size OK (${kb < 1 ? '<1' : kb}KB) ✓`,
    },
    // src/analyzers/schema.js
    schema: {
      notFound: 'No structured data (Schema.org) found — rich snippets not possible',
      found: (n) => `${n} schema block(s) found ✓`,
      noJsonLd: 'No JSON-LD found — use JSON-LD format (Google recommended)',
      hasJsonLd: (n) => `${n} JSON-LD block(s) found ✓`,
      parseErrors: (n) => `${n} JSON-LD block(s) have parse errors — fix the JSON syntax`,
      noErrors: 'All JSON-LD blocks are valid ✓',
      noOrganization: 'No Organization schema — add it for brand knowledge panel',
      hasOrganization: 'Organization schema present ✓',
      noWebSite: 'No WebSite schema — add it for sitelinks search box',
      hasWebSite: 'WebSite schema present ✓',
      noRichResults: 'No rich result eligible schema (FAQ, Product, Review, etc.)',
      hasRichResults: (types) => `Rich result types found: ${types} ✓`,
      noBreadcrumb: 'No BreadcrumbList schema — breadcrumbs won\'t show in Google',
      hasBreadcrumb: 'BreadcrumbList schema present ✓',
      orgMissingFields: (fields) => `Organization schema missing required fields: ${fields}`,
      orgComplete: 'Organization schema has name, url, logo ✓',
    },
  },

  // ─────────────────────────────────────────────────────────
  // HINGLISH (hi)
  // ─────────────────────────────────────────────────────────
  hi: {
    cli: {
      version: "Version dikhao",
      jsonFlag: "Terminal mein JSON output print karo",
      onlyFlag: "Sirf specific modules run karo (comma-separated: seo,performance,tech,accessibility,links)",
      exportFlag: "Report file mein save karo (e.g. --export ./report)",
      formatFlag: "Export format: html | json | both (default: html)",
      noLinksFlag: "Link checking skip karo (faster results)",
      silentFlag: "Spinners aur progress mat dikhao",
      langFlag: "Language: en (default) | hi (Hinglish)",
      exportBoth: "HTML aur JSON dono export karo",
      noArgsHelp: "Usage ke liye --help run karo",
      errorPrefix: "Error",
      errorNotFound: "→ URL check karo, internet connection dekho",
      errorInvalidUrl: "→ Example: website-analyzer https://google.com",
      errorTimeout: "→ Site bahut slow hai ya respond nahi kar rahi",
      errorHelp: "Help ke liye: website-analyzer --help",
      interrupted: "⚠️  Analysis interrupted by user",
    },

    analyze: {
      noUrl: "URL provide karo! Example: website-analyzer https://google.com",
      invalidUrl: (url) => `Invalid URL: "${url}" — sahi URL do, e.g. https://google.com`,
      fetching: (url) => `Fetching ${url}...`,
      fetchDone: (ms, code) => `Fetched! (${ms}ms, HTTP ${code})`,
      fetchFail: "Fetch failed!",
      analyzingSeo: "SEO analyze ho raha hai...",
      seoResult: (pct, grade) => `SEO analyzed — ${pct}% (${grade})`,
      seoFail: "SEO analysis fail ho gayi",
      detectingTech: "Tech stack detect ho raha hai...",
      techResult: (count) => `Tech stack — ${count} technologies detect hui`,
      techFail: "Tech stack detection fail ho gayi",
      analyzingPerf: "Performance analyze ho rahi hai...",
      perfResult: (pct, grade) => `Performance — ${pct}% (${grade})`,
      perfFail: "Performance analysis fail ho gayi",
      analyzingA11y: "Accessibility check ho rahi hai...",
      a11yResult: (pct, grade) => `Accessibility — ${pct}% (${grade})`,
      a11yFail: "Accessibility check fail ho gayi",
      checkingLinks: "Links check ho rahe hain (thoda time lagega)...",
      linksResult: (total, broken) => `Links — ${total} mile, ${broken} broken`,
      linksFail: "Link check fail ho gayi",
      analyzingSecurity: "Security headers check ho rahe hain...",
      securityResult: (pct, grade) => `Security — ${pct}% (${grade})`,
      securityFail: "Security check fail ho gayi",
      analyzingSitemap: "Sitemap analyze ho raha hai...",
      sitemapResult: (pct, grade) => `Sitemap — ${pct}% (${grade})`,
      sitemapFail: "Sitemap analysis fail ho gayi",
      analyzingRobots: "Robots.txt analyze ho raha hai...",
      robotsResult: (pct, grade) => `Robots.txt — ${pct}% (${grade})`,
      robotsFail: "Robots.txt analysis fail ho gayi",
      analyzingSchema: "Structured data analyze ho raha hai...",
      schemaResult: (pct, grade) => `Schema — ${pct}% (${grade})`,
      schemaFail: "Schema analysis fail ho gayi",
      exporting: "Report export ho rahi hai...",
      exportDone: "Report export ho gayi!",
      exportFail: (msg) => `Export fail: ${msg}`,
      analysisError: (name, msg) => `${name} analysis mein error: ${msg}`,
    },

    reporter: {
      title: "🔍 WEBSITE ANALYZER REPORT",
      urlLabel: "URL     : ",
      scannedLabel: "Scanned : ",
      timeLabel: "Time    : ",
      overallScores: "📊 OVERALL SCORES",
      techStack: "🛠️  TECH STACK",
      noTechFound: "Koi technology detect nahi hui",
      catSeo: "SEO",
      catPerformance: "Performance",
      catAccessibility: "Accessibility",
      catLinks: "Links",
      catOverall: "OVERALL",
      colCategory: "Category",
      colScore: "Score",
      colGrade: "Grade",
      colStatus: "Status",
      colBar: "Bar",
      colTechCategory: "Category",
      colTechnologies: "Technologies",
      seoAnalysis: "🔍 SEO ANALYSIS",
      perfAnalysis: "⚡ PERFORMANCE ANALYSIS",
      a11yAnalysis: "♿ ACCESSIBILITY ANALYSIS",
      linksAnalysis: "🔗 LINKS ANALYSIS",
      issues: "❌ Issues (fix karo):",
      warnings: "⚠️  Warnings (improve karo):",
      passed: "✅ Passed:",
      brokenLinks: "🔴 Broken Links:",
      moreLinks: (n) => `... aur ${n} more`,
      redirects: "🔀 Redirects:",
      colLinkType: "Type",
      colCount: "Count",
      totalLinks: "Total Links",
      internalLinks: "Internal Links",
      externalLinks: "External Links",
      brokenLinksCount: "Broken Links",
      redirectCount: "Redirects",
      nofollowCount: "Nofollow",
      mailtoLinks: "Mailto Links",
      telLinks: "Tel Links",
      skipped: "Skipped (limit)",
      colSeoData: "SEO Data",
      colValue: "Value",
      colMetric: "Metric",
      footer: "Made with ❤️  | website-analyzer-cli | github.com/website-analyzer",
      gradeExcellent: "Excellent",
      gradeGood: "Good",
      gradeAverage: "Average",
      gradePoor: "Poor",
      gradeVeryPoor: "Very Poor",
    },

    seo: {
      titleMissing: "Title tag missing hai!",
      titleOk: (t) => `Title: "${t}"`,
      titleTooShort: (n) => `Title ${n} chars ka hai — ideal: 30-60 chars`,
      titleTooLong: (n) => `Title ${n} chars ka hai — ideal: 30-60 chars`,
      titleLengthOk: (n) => `Title length sahi hai (${n} chars)`,
      metaMissing: "Meta description missing hai!",
      metaOk: (d) => `Meta description: "${d}..."`,
      metaLength: (n) => `Meta description ${n} chars — ideal: 120-160`,
      metaLengthOk: (n) => `Meta description length sahi (${n} chars)`,
      canonicalMissing: "Canonical URL set nahi — duplicate content issue ho sakta hai",
      canonicalOk: (c) => `Canonical: ${c}`,
      robotsBlocked: (r) => `robots meta "${r}" — page index nahi hoga Google mein!`,
      robotsOk: (r) => r ? `Robots: ${r}` : "Robots restriction nahi (indexable)",
      ogMissing: "OG tags missing — social media pe preview nahi banega",
      ogPartial: (n) => `Sirf ${n}/5 OG tags set — aur add karo`,
      ogOk: (n) => `OG tags set hain (${n}/5)`,
      twitterMissing: "Twitter card meta missing — Twitter pe preview nahi banega",
      twitterOk: (c) => `Twitter card: ${c}`,
      h1Missing: "H1 heading missing hai — page ka main topic unclear",
      h1Ok: (t) => `H1: "${t}"`,
      h1Multiple: (n) => `${n} H1 tags hain — sirf ek hona chahiye`,
      h1Single: "Ek hi H1 tag hai ✓",
      imgAltMissing: (n, t) => `${n}/${t} images mein alt text missing`,
      imgAltOk: (n) => `Sab ${n} images mein alt text hai ✓`,
      schemaMissing: "Structured data nahi — rich snippets Google mein nahi aayenge",
      schemaOk: (n) => `Schema.org structured data found (${n} script)`,
      viewportMissing: "Viewport meta missing — mobile SEO kharab hoga!",
      viewportOk: (v) => `Viewport: ${v}`,
    },

    performance: {
      noHttps: "Site HTTP use kar raha hai — HTTPS nahi! Security risk + SEO penalty",
      httpsOk: "HTTPS enabled hai ✓",
      responseSlow: (ms) => `Response time ${ms}ms — bahut slow! Hosting/server check karo`,
      responseWarn: (ms) => `Response time ${ms}ms — aur fast ho sakta hai`,
      responseFast: (ms) => `Response time ${ms}ms — fast! ✓`,
      pageLarge: (kb) => `Page size ${kb}KB — bahut bada! Images aur assets compress karo`,
      pageWarn: (kb) => `Page size ${kb}KB — optimize karo`,
      pageOk: (kb) => `Page size ${kb}KB — sahi hai ✓`,
      noCompression: "Content compression nahi — gzip/brotli enable karo, bandwidth bachega",
      compressionOk: (enc) => `Compression: ${enc} ✓`,
      noCache: "Cache headers missing — browser har baar fresh request karega",
      cacheOk: (c) => `Caching set hai (${c || "etag/last-modified"}) ✓`,
      tooManyScripts: (n) => `${n} external scripts — bahut zyada! (ideal: ≤10) Page slow hoga`,
      scriptsOk: (n) => `Script count: ${n} ✓`,
      tooManyStyles: (n) => `${n} stylesheets — zyada hain (ideal: ≤5)`,
      stylesOk: (n) => `Stylesheet count: ${n} ✓`,
      renderBlocking: (n) => `${n} render-blocking scripts — async/defer add karo`,
      noRenderBlocking: "Koi render-blocking script nahi ✓",
      oldImageFormats: (n) => `${n} images old format mein (JPG/PNG) — WebP use karo`,
      modernImages: "Images modern format mein hain ✓",
      badStatus: (code) => `HTTP ${code} — site properly accessible nahi!`,
      statusOk: (code) => `HTTP ${code} OK ✓`,
    },

    accessibility: {
      langMissing: '<html lang="..."> missing — screen readers ko language nahi pata chalegi',
      langOk: (l) => `Language set hai: "${l}" ✓`,
      imgAltMissing: (n, t) => `${n}/${t} images mein alt attribute nahi`,
      imgAltOk: (n) => `Sab ${n} images mein alt text hai ✓`,
      h1Missing: "Page mein koi H1 nahi — main heading missing hai",
      h1Ok: "H1 heading present hai ✓",
      h1Multiple: (n) => `${n} H1 tags hain — sirf 1 hona chahiye`,
      h1Single: "Ek hi H1 hai ✓",
      headingSkip: "Heading levels skip ho rahe hain (e.g. H1 → H3) — H2 missing",
      headingOk: "Heading hierarchy sahi order mein hai ✓",
      inputsUnlabeled: (n, t) => `${n}/${t} form inputs unlabeled — screen readers ke liye problem`,
      inputsOk: (n) => `Sab ${n} form inputs labeled hain ✓`,
      emptyButtons: (n) => `${n} buttons mein text/aria-label nahi — screen readers ke liye invisible`,
      buttonsOk: (n) => `Sab ${n} buttons accessible hain ✓`,
      genericLinks: (links) => `Generic link text mila: ${links.join(", ")} — descriptive text use karo`,
      linksOk: "Links descriptive hain ✓",
      skipNavMissing: "Skip to main content link missing — keyboard users ke liye helpful hota",
      skipNavOk: "Skip navigation link present hai ✓",
      noLandmarks: "Koi ARIA landmark nahi — screen readers ke liye navigate karna mushkil",
      fewLandmarks: (n) => `Sirf ${n}/4 ARIA landmarks — main, nav, header, footer add karo`,
      landmarksOk: (n) => `${n}/4 ARIA landmarks hain ✓`,
      badTabindex: (n) => `${n} elements mein tabindex > 0 — tab order disturb hoga`,
      tabindexOk: "tabindex sahi use ho raha hai ✓",
      zoomDisabled: "Viewport mein zoom disable hai — visually impaired users ke liye problem!",
      zoomOk: "User zoom enabled hai ✓",
    },

    links: {
      brokenFound: (n) => `${n} broken links mile — fix ya remove karo`,
      nobroken: "Koi broken link nahi ✓",
      redirectsFound: (n) => `${n} links redirect kar rahe hain — URLs update karo`,
      noRedirects: "Koi unnecessary redirect nahi ✓",
      noInternal: "Koi internal link nahi — navigation links add karo",
      internalOk: (n) => `${n} internal links hain ✓`,
      noExternal: "Koi external link nahi — trusted sources link karo",
      externalOk: (n) => `${n} external links hain ✓`,
      nofollowOk: (n) => `${n} nofollow links hain (OK) ✓`,
    },

    fetcher: {
      notFound: (url) => `Domain nahi mila: "${url}" — URL check karo`,
      connRefused: "Connection refused: Server ne response nahi diya",
      timeout: (ms) => `Timeout: Website ne ${ms}ms mein respond nahi kiya`,
      fetchError: (msg) => `Fetch error: ${msg}`,
    },

    // src/analyzers/security.js
    security: {
      noHttps: "Site HTTP use kar rahi hai — HTTPS urgently enable karo! Security risk!",
      httpsOk: "HTTPS enabled hai ✓",
      hstsMissing: "Strict-Transport-Security header missing — browsers HTTPS force nahi karenge",
      hstsOk: (v) => `HSTS set hai: ${v} ✓`,
      hstsMaxAge: (n) => `HSTS max-age ${n}s — kam se kam 1 saal (31536000) hona chahiye`,
      hstsMaxAgeOk: (n) => `HSTS max-age ${n}s (>= 1 saal) ✓`,
      cspMissing: "Content-Security-Policy missing — XSS attacks se koi protection nahi",
      cspOk: "CSP header set hai ✓",
      cspUnsafeInline: "CSP mein unsafe-inline hai — XSS risk kam nahi hoga",
      cspUnsafeInlineOk: "CSP mein unsafe-inline nahi ✓",
      cspUnsafeEval: "CSP mein unsafe-eval hai — JS injection risk",
      cspUnsafeEvalOk: "CSP mein unsafe-eval nahi ✓",
      xframeMissing: "X-Frame-Options missing — Clickjacking attack possible hai",
      xframeOk: (v) => `X-Frame-Options: ${v} ✓`,
      xctMissing: "X-Content-Type-Options: nosniff missing — MIME sniffing attack possible",
      xctOk: "X-Content-Type-Options: nosniff ✓",
      referrerWeak: (v) => `Referrer-Policy "${v}" weak hai — strict-origin use karo`,
      referrerMissing: "Referrer-Policy header missing hai",
      referrerOk: (v) => `Referrer-Policy: ${v} ✓`,
      permsMissing: "Permissions-Policy missing — camera/mic/location access restricted nahi",
      permsOk: "Permissions-Policy set hai ✓",
      serverLeaks: (s, x) => [s ? `Server version expose ho rahi: "${s}"` : "", x ? `X-Powered-By expose ho raha: "${x}" — hata do!` : ""].filter(Boolean).join(" | "),
      serverHidden: "Server info hidden hai ✓",
      mixedContent: (n) => `${n} HTTP resources HTTPS page pe mile — browser block kar sakta hai`,
      noMixedContent: "Koi mixed content nahi ✓",
      corsWildcard: "Access-Control-Allow-Origin: * — sab domains allowed! Restrict karo",
      corsOk: (v) => `CORS restricted hai: ${v} ✓`,
    },
    // src/analyzers/sitemap.js
    sitemap: {
      notFound: 'Sitemap.xml nahi mila — Google crawling affected hogi',
      found: (url) => `Sitemap mila: ${url} ✓`,
      indexEmpty: 'Sitemap index mila par usme koi child sitemap nahi',
      indexFound: (n) => `Sitemap index mein ${n} sitemaps hain ✓`,
      noUrls: 'Sitemap mein koi URL nahi — sitemap generator check karo',
      urlCount: (n) => `Sitemap mein ${n} URLs hain ✓`,
      tooLarge: (n) => `Sitemap mein ${n} URLs hain — 50,000 limit exceed! Multiple sitemaps banao`,
      sizeOk: (n) => `Sitemap size theek hai (${n} URLs) ✓`,
      noLastmod: 'Lastmod dates nahi hain — better crawling ke liye add karo',
      hasLastmod: 'Sitemap mein lastmod dates hain ✓',
      invalidXml: 'Sitemap XML format invalid hai',
      validXml: 'Sitemap XML valid hai ✓',
      httpUrls: (n) => `Sitemap mein ${n} URLs HTTP use kar rahe hain — HTTPS karo`,
      httpsUrls: 'Sitemap ke sab URLs HTTPS use kar rahe hain ✓',
    },
    // src/analyzers/robots.js
    robots: {
      notFound: 'robots.txt nahi mila — crawlers ko koi instructions nahi',
      found: (url) => `robots.txt mila: ${url} ✓`,
      noSitemapRef: 'robots.txt mein Sitemap reference nahi — Sitemap: https://yoursite.com/sitemap.xml add karo',
      hasSitemapRef: (url) => `Sitemap referenced: ${url} ✓`,
      noWildcard: 'User-agent: * rule nahi hai — sab crawlers ke liye default instructions nahi',
      hasWildcard: 'Wildcard User-agent (*) defined hai ✓',
      blocksAll: 'Disallow: / sab crawlers ke liye — poori site indexing se block hai!',
      notBlockingAll: 'Site sab crawlers ko block nahi kar rahi ✓',
      noGooglebot: 'Googlebot ke liye koi rules nahi — Google crawler ke liye specific rules add karo',
      hasGooglebot: 'Googlebot rules defined hain ✓',
      crawlDelayHigh: (n) => `Crawl-delay: ${n}s bahut zyada hai — crawlers slow ho jayenge`,
      crawlDelayOk: (n) => `Crawl-delay: ${n}s theek hai ✓`,
      noSensitiveBlock: 'Koi sensitive paths block nahi (/admin, /login) — block karne par vichar karo',
      hasSensitiveBlock: (paths) => `Sensitive paths block hain: ${paths} ✓`,
      tooLarge: (kb) => `robots.txt ${kb}KB ka hai — bahut bada, 500KB se kam rakho`,
      sizeOk: (kb) => `robots.txt size theek hai (${kb < 1 ? '<1' : kb}KB) ✓`,
    },
    // src/analyzers/schema.js
    schema: {
      notFound: 'Koi structured data (Schema.org) nahi mila — rich snippets possible nahi',
      found: (n) => `${n} schema block(s) mile ✓`,
      noJsonLd: 'JSON-LD nahi mila — JSON-LD format use karo (Google recommended)',
      hasJsonLd: (n) => `${n} JSON-LD block(s) mile ✓`,
      parseErrors: (n) => `${n} JSON-LD block(s) mein parse errors hain — JSON syntax fix karo`,
      noErrors: 'Sab JSON-LD blocks valid hain ✓',
      noOrganization: 'Organization schema nahi — brand knowledge panel ke liye add karo',
      hasOrganization: 'Organization schema present hai ✓',
      noWebSite: 'WebSite schema nahi — sitelinks search box ke liye add karo',
      hasWebSite: 'WebSite schema present hai ✓',
      noRichResults: 'Koi rich result eligible schema nahi (FAQ, Product, Review, etc.)',
      hasRichResults: (types) => `Rich result types mile: ${types} ✓`,
      noBreadcrumb: 'BreadcrumbList schema nahi — Google mein breadcrumbs nahi dikhenge',
      hasBreadcrumb: 'BreadcrumbList schema present hai ✓',
      orgMissingFields: (fields) => `Organization schema mein zaroori fields missing: ${fields}`,
      orgComplete: 'Organization schema mein name, url, logo sab hain ✓',
    },
  },
};

// ─────────────────────────────────────────
// ACTIVE LANGUAGE CONFIG
// ─────────────────────────────────────────

let activeLang = "en"; // default

function setLang(lang) {
  if (lang === "hi" || lang === "en") {
    activeLang = lang;
  } else {
    console.warn(`Unknown language "${lang}", falling back to English.`);
    activeLang = "en";
  }
}

function getLang() {
  return activeLang;
}

/**
 * t(key) — Get translated string
 * key format: "section.key" e.g. "seo.titleMissing"
 *
 * For function strings: t('seo.titleOk')('My Title')
 */
function t(key) {
  const parts = key.split(".");
  let val = strings[activeLang];
  for (const part of parts) {
    if (val === undefined) break;
    val = val[part];
  }
  // Fallback to English if key missing in Hinglish
  if (val === undefined) {
    val = strings["en"];
    for (const part of parts) {
      if (val === undefined) break;
      val = val[part];
    }
  }
  return val;
}

module.exports = { t, setLang, getLang };
