name = "website-analyzer-api"
main = "src/index.js"
compatibility_date = "2024-09-23"   
compatibility_flags = ["nodejs_compat"]

[dev]
port = 8787
local_protocol = "http"

[[d1_databases]]
binding = "DB"
database_name = "website-analyzer-db"
database_id = "1cb085e3-0cb9-47c3-afd3-2cc0db39c4a1"

[vars]
ENVIRONMENT = "development"
API_VERSION = "v1"
FREE_CREDITS = "20"

[env.production]
name = "website-analyzer-api-prod"

[env.production.vars]
ENVIRONMENT = "production"
